Repository PEANUTBUTTER1001/carefull, pull requests merged in 2025-07, with the labels that each got.

#21 feat: 네이버 지도 API 연동, 진단에 따른 병원 정보 화면 구현 진행중
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/openstudy/carefull/hospitalInfo/HospitalInfoScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨ feat

#28 feat: 원하는 질병에 대한 검색 화면 구현 진행중
  app/src/main/java/com/openstudy/carefull/disease/DiseaseInfo.kt
  app/src/main/java/com/openstudy/carefull/disease/DiseaseSearchScreen.kt
Labels: ✨ feat

#29 feat: 지도 401 오류 해결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
Labels: 🐛 fix

#32 feat: 약 검색 결과 화면 구현 중 / feat: 챗봇 기능 구현 중 / chore: 모듈 이름 변경, 패키지 리팩토링
  app/build.gradle.kts
  app/src/main/java/com/openstudy/carefull/MainActivity.kt
  app/src/main/java/com/openstudy/carefull/chatbot/ChatMessage.kt
  app/src/main/java/com/openstudy/carefull/common/CarefullApplication.kt
  app/src/main/java/com/openstudy/carefull/di/AppModule.kt
  app/src/main/java/com/openstudy/carefull/medicineInfo/MedicineInfoScreen.kt
  app/src/main/java/com/openstudy/carefull/navigation/BarList.kt
  app/src/main/java/com/openstudy/carefull/navigation/Navigation.kt
  app/src/main/java/com/openstudy/carefull/screen/chatbot/ChatbotScreen.kt
  app/src/main/java/com/openstudy/carefull/screen/disease/DiseaseSearchScreen.kt
  app/src/main/java/com/openstudy/carefull/screen/hospital/HospitalInfoScreen.kt
  app/src/main/java/com/openstudy/carefull/screen/hospital/HospitalSearchScreen.kt
  app/src/main/java/com/openstudy/carefull/screen/medicine/MedicineInfoScreen.kt
  app/src/main/java/com/openstudy/carefull/screen/medicine/MedicineSearchScreen.kt
  app/src/main/java/com/openstudy/carefull/viewmodel/ChatBotViewModel.kt
  app/src/main/java/com/openstudy/carefull/viewmodel/MedicineViewModel.kt
  build.gradle.kts
  data/build.gradle.kts
  data/src/androidTest/java/com/openstudy/carefull/data/ExampleInstrumentedTest.kt
  data/src/main/java/com/openstudy/carefull/data/model/ChatBotMessageInfo.kt
  data/src/main/java/com/openstudy/carefull/data/model/DiseaseInfo.kt
  data/src/main/java/com/openstudy/carefull/data/model/MedicineInfo.kt
  data/src/main/java/com/openstudy/carefull/data/network/MedicineApiService.kt
  data/src/main/java/com/openstudy/carefull/data/network/MedicineResponse.kt
  data/src/main/java/com/openstudy/carefull/data/repository/MedicineRepository.kt
  data/src/test/java/com/openstudy/carefull/data/ExampleUnitTest.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  shared/build.gradle.kts
  shared/src/androidTest/java/com/openstudy/carefull/shared/ExampleInstrumentedTest.kt
  shared/src/main/java/com/openstudy/carefull/shared/constants/example.kt
  shared/src/main/java/com/openstudy/carefull/shared/utils/example.kt
  shared/src/test/java/com/openstudy/carefull/shared/ExampleUnitTest.kt
Labels: 🐛 fix, ♻️ refactor, ⚙️ chore

#33 refactor: 식단(Diet) 탭 Clean Architecture 구조 적용 / fix: 네비게이션바 색상적용 오류 수정
  app/build.gradle.kts
  app/src/main/java/com/openstudy/carefull/navigation/BarList.kt
  app/src/main/java/com/openstudy/carefull/navigation/Navigation.kt
  app/src/main/java/com/openstudy/carefull/navigation/NavigationBar.kt
  app/src/main/java/com/openstudy/carefull/screen/auth/Signin.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/FoodInformation.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/SearchFood.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/diet_app/DietScreen.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/diet_app/DietViewModel.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/diet_app/di/RepositoryModule.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/diet_data/ApiResponse.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/diet_data/repository/DietRepositoryImpl.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/diet_shared/model/Meal.kt
  app/src/main/java/com/openstudy/carefull/screen/routine/diet_shared/repository/DietRepository.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🐛 fix, ♻️ refactor
